// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC7A5b4kLHtr72Ft24GCRbncNvIq93vNU',
    appId: '1:631393054820:web:98dfae3cd94512bb476f71',
    messagingSenderId: '631393054820',
    projectId: 'chatboat-971b8',
    authDomain: 'chatboat-971b8.firebaseapp.com',
    storageBucket: 'chatboat-971b8.firebasestorage.app',
    measurementId: 'G-51TS2YBG2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpKVyEAZrFWINULBXFINbJkVxW4e_dlQI',
    appId: '1:631393054820:android:3cfa49425e8017f0476f71',
    messagingSenderId: '631393054820',
    projectId: 'chatboat-971b8',
    storageBucket: 'chatboat-971b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPb7knnldKau-JZR9CPh2e-mqcd1BEj8',
    appId: '1:631393054820:ios:63fefef254a1d7a7476f71',
    messagingSenderId: '631393054820',
    projectId: 'chatboat-971b8',
    storageBucket: 'chatboat-971b8.firebasestorage.app',
    iosBundleId: 'com.example.chatboat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPb7knnldKau-JZR9CPh2e-mqcd1BEj8',
    appId: '1:631393054820:ios:63fefef254a1d7a7476f71',
    messagingSenderId: '631393054820',
    projectId: 'chatboat-971b8',
    storageBucket: 'chatboat-971b8.firebasestorage.app',
    iosBundleId: 'com.example.chatboat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC7A5b4kLHtr72Ft24GCRbncNvIq93vNU',
    appId: '1:631393054820:web:60cfec8206437048476f71',
    messagingSenderId: '631393054820',
    projectId: 'chatboat-971b8',
    authDomain: 'chatboat-971b8.firebaseapp.com',
    storageBucket: 'chatboat-971b8.firebasestorage.app',
    measurementId: 'G-05RV4PC9TS',
  );
}
